#!/bin/bash
#XXX This helper script is bogus and only works for the example config.
#XXX Absolute names need to be passed in or computed!
#XXX Need to let SPDK config file configure DRBD also.

sleep .5	# XXXXX let fuse thread finish mounting /UMCfuse
set -v

drbdmeta 2 v09 /tmp/tcmur_ram01 internal create-md 2 --force	# Ugh

drbdsetup new-resource $1 2
drbdsetup new-minor $1 2 0
drbdsetup new-peer spdk 0 --_name=blackbox		# Protocol C is the default
### drbdsetup new-peer spdk 0 --_name=blackbox --congestion-fill=1024s --on-congestion=pull-ahead --protocol=A
drbdsetup new-path $1 0 ipv4:192.168.1.23:7788 ipv4:192.168.1.22:7788
drbdsetup peer-device-options $1 0 0 --c-plan-ahead=0 --resync-rate=40000K --c-min-rate=0k
drbdsetup attach 2 $2 $2 internal
drbdsetup connect $1 0

drbdadm primary $1 --force

